CREATE DATABASE IF NOT EXISTS CAR;
USE CAR;

CREATE TABLE IF NOT EXISTS CAR (
	VIN INT PRIMARY KEY,
	MODEL VARCHAR(20) NOT NULL,
    BRAND VARCHAR(20) NOT NULL,
    COLOR VARCHAR(20) DEFAULT "WHITE",
    PRICE INT NOT NULL,
    MAX_SPEED INT
);

SHOW TABLES;

INSERT INTO CAR VALUES (1453342, "KALINA", "LADA", "BLACK", 300, 400);
INSERT INTO CAR(VIN, MODEL, BRAND, COLOR, PRICE, MAX_SPEED) VALUES (41541, "VESTA", "LADA", "RED", 500, 100);

SELECT * FROM CAR WHERE COLOR IS NOT NULL;
SELECT MODEL, BRAND FROM CAR WHERE PRICE < 400;

UPDATE CAR SET MAX_SPEED = 100 WHERE VIN = 1453342 AND BRAND = "lada";

DELETE FROM CAR WHERE COLOR IS NULL;

SELECT * FROM CAR;


